In [3]:
import pandas as pd
import dhlab as dh

In [4]:
romance = pd.read_csv("urn_to_romance.csv")

In [8]:
romance.sort_values(by="tag").head()

                                     urn             counts  tag
124                                  NaN  Counter({'w': 1})  w-1
66   URN:NBN:no-nb_digibok_2010100608041  Counter({'w': 1})  w-1
64   URN:NBN:no-nb_digibok_2010100608041  Counter({'w': 1})  w-1
125  URN:NBN:no-nb_digibok_2017020148100  Counter({'w': 1})  w-1
90   URN:NBN:no-nb_digibok_2009100812001  Counter({'w': 1})  w-1

In [11]:
romance_counts= dh.Counts(romance.dropna().urn)

In [12]:
romance_counts = romance_counts.frame

In [14]:
romance_counts.to_csv('romance_counts.csv')

In [15]:
#romance["tag"].values

In [16]:
#romance.sort_values(by="tag").style

In [34]:
corpus_1800 = pd.read_excel("1800-1839.xlsx")

In [35]:
atten00 = dh.Corpus()

atten00.extend_from_identifiers(corpus_1800.urn)

atten00 = atten00.frame

atten00.dhlabid = atten00.dhlabid.astype(int)

In [36]:
atten00.head()

,urn,dhlabid,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,URN:NBN:no-nb_digibok_2007072303002,100614911,Den hjemkomne Søn eller En Nutidens Jean de Fr...,"Blom , Hans Ørn / Dahl , Johan ( Johan Fjeldst...",oai:nb.bibsys.no:999509497954702202,c8dfc01023ebb29241261fdda667eb53,,,18390101.0,1839.0,Forlagt af Johan Dahl,dan,Norsk litteratur / 1800-tallet,,drama,Skjønnlitteratur,digibok,dhlab,20221201.0
1,URN:NBN:no-nb_digibok_2007072703001,100628186,En norsk Höst : Et Digt,"Zetlitz , Jens / Liunge , Poul Munkgaard / Pop...",oai:nb.bibsys.no:999912973004702202,30587a45784a22b45a099dbb9c38d98a,,,18000101.0,1800.0,"Trykt paa Boghandler P. M. Liunges Forlag, hos...",dan,Norsk litteratur / Dansk litteratur / 1700-tallet,,poetry,Skjønnlitteratur,digibok,dhlab,20221209.0
2,URN:NBN:no-nb_digibok_2007082703001,100628222,Digtninger : Anden Deel,"Hansen , Maurits / Høeg , T. A. ( Tønnes Andre...",oai:nb.bibsys.no:999820450424702202,84aeba249e51fb71b92eac647682f589,,,18250101.0,1825.0,Trykt af T. A. Høeg,dan,Norsk litteratur / 1800-tallet,,fiction,Skjønnlitteratur,digibok,dhlab,20221209.0
3,URN:NBN:no-nb_digibok_2007102402004,100628262,Samlede poetiske Forsøg,"Wolff , S. O. ( Simon Olaus ) / Winther , Hans...",oai:nb.bibsys.no:990306049154702202,f1733fdf0007d7b1611544405f8dcafe,,,18330101.0,1833.0,Paa H. T. Winthers Forlag. Trykt i Forlæggeren...,dan,Norsk litteratur / 1800-tallet,,poetry,Skjønnlitteratur,digibok,dhlab,20221209.0
4,URN:NBN:no-nb_digibok_2008010810007,100628326,Den indiske Cholera : Drama,"Wergeland , Henrik / Roshauw , Carl L.",oai:nb.bibsys.no:990302759894702202,41dabe1e53dcd68b42ce6dce890ead08,,,18350101.0,1835.0,Trykt i det Lundhske Bogtrykkeri af C. L. Roshauw,dan,Norsk litteratur / 1800-tallet,,drama,Skjønnlitteratur,digibok,dhlab,20221209.0

In [17]:
corpus_1840 = pd.read_excel("1840-1869.xlsx")

In [18]:
corpus_1840

                                     urn
0    URN:NBN:no-nb_digibok_2007112610011
1    URN:NBN:no-nb_digibok_2008110612005
2    URN:NBN:no-nb_digibok_2012042724002
3    URN:NBN:no-nb_digibok_2008102912002
4    URN:NBN:no-nb_digibok_2012061313001
..                                   ...
234  URN:NBN:no-nb_digibok_2017012648103
235  URN:NBN:no-nb_digibok_2019121748050
236  URN:NBN:no-nb_digibok_2009081403018
237  URN:NBN:no-nb_digibok_2009071303001
238  URN:NBN:no-nb_digibok_2006111400031

[239 rows x 1 columns]

In [22]:
atten40 = dh.Corpus()

atten40.extend_from_identifiers(corpus_1840.urn)

atten40 = atten40.frame

atten40.dhlabid = atten40.dhlabid.astype(int)

In [33]:
atten40.head()

,urn,dhlabid,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,URN:NBN:no-nb_digibok_2006082500010,100614143,Lord William Russell : historisk Tragoedie i f...,"Munch , A.",oai:nb.bibsys.no:999510400144702202,1b6b46162c1eb8e1d536863410a5d214,,Christiania,18570101.0,1857.0,Tønsbergs Forl.,nob,,,,Uklassifisert,digibok,dhlab,20221201.0
1,URN:NBN:no-nb_digibok_2006082800071,100614175,Fraa Bygdom,"Janson , Kristofer",oai:nb.bibsys.no:999205353214702202,16172baab957a7595d1de164d8905c2e,,Bjørgvin,18660101.0,1866.0,Giertsen,nno,,,,Uklassifisert,digibok,dhlab,20221201.0
2,URN:NBN:no-nb_digibok_2006082900008,100628018,Jon Arason : Syrgespil i 5 Aktar,"Janson , Kristofer",oai:nb.bibsys.no:999503521014702202,f1a9467f2196c46ab0f1171dfd384983,,Bjørgvin,18670101.0,1867.0,Giertsen,nno,,,,Uklassifisert,digibok,dhlab,20221209.0
3,URN:NBN:no-nb_digibok_2006111400028,100614245,I de lange Nætter,"Collett , Camilla",oai:nb.bibsys.no:999407148844702202,37246857b59a4cadb5601eb2983c092c,,Christiania,18630101.0,1863.0,Cappelen,nob,,,,Uklassifisert,digibok,dhlab,20221201.0
4,URN:NBN:no-nb_digibok_2006111400031,100628036,Lauvduskar. 1/2,,oai:nb.bibsys.no:999430112644702202,cf2a22a1821dc7b51c96391b204a2334,,Kristiania,18680101.0,1868.0,Samlaget,nno,,,fiction,Skjønnlitteratur,digibok,dhlab,20221209.0

In [31]:
#count1840 = dh.Counts(atten40)

In [39]:
#count1840.frame.to_csv("counts_1840.csv")

In [2]:
#count1840.frame.to_parquet("count1840.pqt")

In [26]:
count1840 = pd.read_csv('counts_1840.csv', index_col=0)

In [27]:
count1840

,100614143,100614175,100614245,100614693,100614877,100614914,100614922,100615157,100615227,100615665,...,100636101,100636104,100636110,100636170,100636290,100636310,100636361,100636398,100636444,100484948
",",2315.0,4505.0,5163.0,1854.0,902.0,1175.0,9632.0,1266.0,307.0,2884.0,...,1864.0,4662.0,2023.0,2254.0,1047.0,472.0,6429.0,8778.0,935.0,2744.0
.,1769.0,2353.0,2369.0,1366.0,449.0,1201.0,3798.0,628.0,75.0,1713.0,...,534.0,1647.0,690.0,1855.0,653.0,359.0,1583.0,1832.0,531.0,1246.0
–,1249.0,277.0,253.0,628.0,39.0,222.0,847.0,176.0,0.0,204.0,...,463.0,136.0,47.0,628.0,162.0,11.0,159.0,596.0,11.0,83.0
!,480.0,178.0,518.0,679.0,146.0,333.0,140.0,159.0,19.0,146.0,...,87.0,115.0,79.0,887.0,267.0,71.0,643.0,311.0,16.0,52.0
jeg,363.0,2.0,971.0,390.0,70.0,256.0,1204.0,86.0,24.0,306.0,...,146.0,446.0,536.0,486.0,129.0,32.0,470.0,980.0,59.0,169.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Huustruen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
~,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0
Barbara,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
Uhrmageren,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
stricte,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0

In [32]:
toks = [x for x in count1840.index if not str(x).isalpha() and len(x) == 1]

In [31]:
conc = dh.Concordance(atten40, "€")
conc.size

0

In [37]:
count1800 = dh.Counts(corpus_1800)

In [38]:
count1800

,100614911,100615228,100615801,100615808,100615913,100616628,100616675,100618743,100619946,100623920,...,100636209,100636213,100636215,100636286,100636287,100636329,100636402,100636410,100636445,100636458
.,1919.0,360.0,34.0,182.0,1612.0,538.0,106.0,290.0,781.0,1608.0,...,823.0,5525.0,140.0,1704.0,3203.0,395.0,189.0,123.0,998.0,164.0
",",1646.0,337.0,54.0,797.0,1250.0,1273.0,432.0,441.0,2765.0,2870.0,...,2005.0,7937.0,282.0,3300.0,2114.0,599.0,352.0,313.0,3084.0,336.0
at,612.0,33.0,0.0,52.0,217.0,73.0,77.0,38.0,288.0,226.0,...,312.0,1238.0,12.0,515.0,647.0,109.0,23.0,34.0,672.0,65.0
!,529.0,144.0,10.0,34.0,190.0,135.0,37.0,163.0,471.0,480.0,...,189.0,1720.0,144.0,262.0,1482.0,139.0,46.0,20.0,125.0,27.0
jeg,523.0,21.0,0.0,6.0,268.0,109.0,30.0,94.0,198.0,237.0,...,165.0,1255.0,29.0,149.0,715.0,77.0,58.0,25.0,268.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
önlkede,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Amali,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Foölelse,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Doctorinden,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
malie,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [39]:
count1800 = count1800.frame

In [40]:
count1800

,100614911,100615228,100615801,100615808,100615913,100616628,100616675,100618743,100619946,100623920,...,100636209,100636213,100636215,100636286,100636287,100636329,100636402,100636410,100636445,100636458
.,1919.0,360.0,34.0,182.0,1612.0,538.0,106.0,290.0,781.0,1608.0,...,823.0,5525.0,140.0,1704.0,3203.0,395.0,189.0,123.0,998.0,164.0
",",1646.0,337.0,54.0,797.0,1250.0,1273.0,432.0,441.0,2765.0,2870.0,...,2005.0,7937.0,282.0,3300.0,2114.0,599.0,352.0,313.0,3084.0,336.0
at,612.0,33.0,0.0,52.0,217.0,73.0,77.0,38.0,288.0,226.0,...,312.0,1238.0,12.0,515.0,647.0,109.0,23.0,34.0,672.0,65.0
!,529.0,144.0,10.0,34.0,190.0,135.0,37.0,163.0,471.0,480.0,...,189.0,1720.0,144.0,262.0,1482.0,139.0,46.0,20.0,125.0,27.0
jeg,523.0,21.0,0.0,6.0,268.0,109.0,30.0,94.0,198.0,237.0,...,165.0,1255.0,29.0,149.0,715.0,77.0,58.0,25.0,268.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
önlkede,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Amali,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Foölelse,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Doctorinden,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
malie,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [41]:
count1840

,100614143,100614175,100614245,100614693,100614877,100614914,100614922,100615157,100615227,100615665,...,100636101,100636104,100636110,100636170,100636290,100636310,100636361,100636398,100636444,100484948
",",2315.0,4505.0,5163.0,1854.0,902.0,1175.0,9632.0,1266.0,307.0,2884.0,...,1864.0,4662.0,2023.0,2254.0,1047.0,472.0,6429.0,8778.0,935.0,2744.0
.,1769.0,2353.0,2369.0,1366.0,449.0,1201.0,3798.0,628.0,75.0,1713.0,...,534.0,1647.0,690.0,1855.0,653.0,359.0,1583.0,1832.0,531.0,1246.0
–,1249.0,277.0,253.0,628.0,39.0,222.0,847.0,176.0,0.0,204.0,...,463.0,136.0,47.0,628.0,162.0,11.0,159.0,596.0,11.0,83.0
!,480.0,178.0,518.0,679.0,146.0,333.0,140.0,159.0,19.0,146.0,...,87.0,115.0,79.0,887.0,267.0,71.0,643.0,311.0,16.0,52.0
jeg,363.0,2.0,971.0,390.0,70.0,256.0,1204.0,86.0,24.0,306.0,...,146.0,446.0,536.0,486.0,129.0,32.0,470.0,980.0,59.0,169.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Huustruen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
~,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0
Barbara,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
Uhrmageren,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
stricte,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0

In [42]:
romance_counts

,100628008,100628009,100628017,100628097,100628159,100628177,100628222,100628227,100628238,100628331,...,100071871,100102006,100114358,100346794,100364575,100584416,100604100,100440317,300186128,300149622
",",5286.0,7893.0,13641.0,9194.0,935.0,1432.0,3627.0,4577.0,4617.0,39632.0,...,10327.0,782.0,4318.0,4262.0,16537.0,535.0,24103.0,19920.0,4760.0,11099.0
.,2406.0,3920.0,9542.0,4172.0,402.0,636.0,2148.0,1568.0,5055.0,20162.0,...,5175.0,720.0,1953.0,1910.0,8871.0,311.0,14729.0,12324.0,4758.0,6081.0
og,2374.0,3953.0,5043.0,4192.0,171.0,355.0,1535.0,1307.0,904.0,16007.0,...,3850.0,448.0,2050.0,1897.0,5216.0,338.0,7918.0,9828.0,2909.0,3001.0
i,1337.0,2387.0,4768.0,3056.0,170.0,280.0,742.0,886.0,681.0,12363.0,...,3477.0,181.0,1299.0,841.0,4453.0,108.0,6442.0,7677.0,1976.0,3141.0
!,1155.0,36.0,155.0,163.0,159.0,161.0,632.0,674.0,2678.0,385.0,...,145.0,49.0,157.0,91.0,1645.0,6.0,1758.0,343.0,124.0,129.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
á,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0
þá,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0
ÆLDSTE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0
UDSEENDE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,56.0
SPROGS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.0

In [56]:
romance_counts.sum(axis = 1)

,           1327212.0
.           1070581.0
og           367796.0
i            280468.0
!             65026.0
              ...
á                39.0
þá               40.0
ÆLDSTE           44.0
UDSEENDE         56.0
SPROGS           59.0
Length: 806504, dtype: float64

In [48]:
rom = romance_counts.sum(axis = 1)

In [45]:
forty = count1840.sum(axis = 1)

In [46]:
zero = count1800.sum(axis = 1)

In [59]:
zero.loc[zero.index.duplicated()]

Series([], dtype: float64)

In [91]:
fnonan = forty.loc[forty.index != n]

In [70]:
rom.loc[rom.index.duplicated()]

Series([], dtype: float64)

In [99]:
nonan = fnonan.loc[[x for x in fnonan.index if isinstance(x, str)]]

In [100]:
nonan.loc[nonan.index.duplicated()]

Series([], dtype: float64)

In [101]:
combo = pd.concat([zero, nonan, rom], axis = 1)

In [102]:
combo.columns = ["1800", "1840", "NatRom"]

In [107]:
combo_rel = combo*100/combo.sum()

In [108]:
combo_rel

              1800      1840    NatRom
.         4.315781  4.080860  6.554163
,         7.733301  7.824024  8.125274
at        1.286874  1.543877  1.302707
!         1.208910  0.813258  0.398093
jeg       0.991235  0.954638  0.439864
...            ...       ...       ...
á              NaN       NaN  0.000239
þá             NaN       NaN  0.000245
ÆLDSTE         NaN       NaN  0.000269
UDSEENDE       NaN       NaN  0.000343
SPROGS         NaN       NaN  0.000361

[983085 rows x 3 columns]

Råforskjeller

In [111]:
combo_rel['diff_00'] = combo_rel['NatRom']/combo_rel['1800']
combo_rel['diff_40'] = combo_rel['NatRom']/combo_rel['1840']

In [125]:
combo.sum()

1800       2.811542e+06
1840       8.908613e+06
NatRom     1.633437e+07
diff_00    6.822047e+05
diff_40    5.251001e+05
dtype: float64

In [124]:
combo.loc[combo.index.str.contains('[Pp]atrio')]

                         1800  1840  NatRom    diff_00    diff_40
Patriot                  18.0  20.0    29.0   1.611111   1.450000
patriotist                2.0   3.0     6.0   3.000000   2.000000
patriotisk                9.0   9.0    28.0   3.111111   3.111111
Patrioter                 4.0  14.0    29.0   7.250000   2.071429
Patriotieme               1.0   NaN     NaN        NaN        NaN
Patriotisme               6.0   8.0    50.0   8.333333   6.250000
patriotiske               3.0  18.0    84.0  28.000000   4.666667
Nationalblads-Patrioten   1.0   NaN     NaN        NaN        NaN
Patriotismen              1.0   1.0    11.0  11.000000  11.000000
Patrioten                 4.0   4.0     3.0   0.750000   0.750000
varmpatriotisk            1.0   NaN     NaN        NaN        NaN
Mundpatrioter             1.0   NaN     NaN        NaN        NaN
Patriotismus              1.0   1.0     NaN        NaN        NaN
Patriotens                1.0   1.0     2.0   2.000000   2.000000
Storpatrioterne           1.0   NaN     NaN        NaN        NaN
Patrioters                1.0   1.0     NaN        NaN        NaN
Patriotiske               1.0   NaN     1.0   1.000000        NaN
patriotiskte              NaN   1.0     1.0        NaN   1.000000
patriotiste               NaN   2.0     2.0        NaN   1.000000
Patriotismens             NaN   1.0     4.0        NaN   4.000000
patrioter                 NaN   1.0     1.0        NaN   1.000000
økonomisk-patriotiske     NaN   1.0     NaN        NaN        NaN
patriotift                NaN   1.0     1.0        NaN   1.000000
Ikkepatriot               NaN   1.0     NaN        NaN        NaN
KraftPatrioternes         NaN   1.0     NaN        NaN        NaN
Patrioternes              NaN   NaN     2.0        NaN        NaN
Patriotismes              NaN   NaN     2.0        NaN        NaN
Patriots                  NaN   NaN     2.0        NaN        NaN
patriolift                NaN   NaN     1.0        NaN        NaN
patriotisf                NaN   NaN     1.0        NaN        NaN
patriotistt               NaN   NaN     1.0        NaN        NaN
upatriotift               NaN   NaN     1.0        NaN        NaN
upatriotisk               NaN   NaN     1.0        NaN        NaN
patriotisfe               NaN   NaN     2.0        NaN        NaN
patriotiskt               NaN   NaN     2.0        NaN        NaN
patriotifte               NaN   NaN     3.0        NaN        NaN
Borger-Patriot            NaN   NaN     1.0        NaN        NaN
Patrioterne               NaN   NaN     2.0        NaN        NaN
kraftpatriotisme          NaN   NaN     1.0        NaN        NaN
patriotisk-kraftig        NaN   NaN     1.0        NaN        NaN
patriotisksindede         NaN   NaN     1.0        NaN        NaN
patriotiskukritiske       NaN   NaN     1.0        NaN        NaN
Gotkaups-Patrioter        NaN   NaN     2.0        NaN        NaN
Patrioti                  NaN   NaN     1.0        NaN        NaN
kraftpatriotist           NaN   NaN     1.0        NaN        NaN
falsk-patriotiske         NaN   NaN     1.0        NaN        NaN
patriotisk-exclusive      NaN   NaN     1.0        NaN        NaN
speciel-patriotiske       NaN   NaN     1.0        NaN        NaN
patrio                    NaN   NaN     2.0        NaN        NaN
Ikkepatrioter             NaN   NaN     1.0        NaN        NaN
Patriotismø               NaN   NaN     1.0        NaN        NaN
Patriotisk                NaN   NaN     4.0        NaN        NaN
kraftpatriotisk           NaN   NaN     1.0        NaN        NaN
Bygdepatriotisme          NaN   NaN     2.0        NaN        NaN
patrios                   NaN   NaN     1.0        NaN        NaN
patriotisme               NaN   NaN     5.0        NaN        NaN
Patriofcr                 NaN   NaN     1.0        NaN        NaN
Patrioternc               NaN   NaN     1.0        NaN        NaN
SPatriottéme              NaN   NaN     1.0        NaN        NaN
patriotismen              NaN   NaN     3.0        NaN        NaN
patriot                   NaN   NaN     2.0        NaN        NaN
patriotiffe               NaN   NaN     2.0        NaN        NaN
patrioten                 NaN   NaN     2.0        NaN        NaN
Patriotenes               NaN   NaN     1.0        NaN        NaN
Patriotism                NaN   NaN     1.0        NaN        NaN
patriotenes               NaN   NaN     1.0        NaN        NaN
patriotismes              NaN   NaN     1.0        NaN        NaN
Patriotene                NaN   NaN     2.0        NaN        NaN

In [131]:
combo_rel.loc[combo.index.str.contains('[Pp]atrio')].sort_values(by="NatRom", ascending=False).head(50).style.background_gradient()

In [128]:
combo_rel.loc[combo.index.str.contains('[Ss]avn|[lL]ængs')].sort_values(by="diff_00", ascending=False).head(10).style.background_gradient()

In [130]:
combo_rel.loc[combo.index.str.contains('[Nn]a.*on.*')].sort_values(by="diff_00", ascending=False).head(10).style.background_gradient()

In [142]:
tot = combo[["1800", "1840", "NatRom"]].sum(axis = 1)

In [152]:
def make_coll(corpus, words):
    coll = dh.Collocations(corpus,words, before = 5, after = 5).frame
    coll.sort_values(by = 'counts', ascending=False)
    coll['diff'] = (coll['counts']/coll['counts'].sum())/(tot/tot.sum())
    return coll

In [157]:
collnat = make_coll(list(romance.dropna().urn), ['Patriot', 'patriotisk', 'patriotiske',"Patrioter"])

In [160]:
coll40 = make_coll(list(atten40.dropna().urn), ['Patriot', 'patriotisk', 'patriotiske',"Patrioter"])

In [158]:
showcoll = lambda coll: coll[coll['counts'] > 1].sort_values(by="diff", ascending = False).head(50)

In [161]:
showcoll(collnat).head(10)

            counts          diff
Harleqvin        2  16502.660000
Daniens          2   8251.330000
Panthea          2   3300.532000
Harlekin         5   2357.522857
velmente         4   2276.228966
Ornamenter       2   1941.489412
Jernbaner        2   1650.266000
velmeente        4   1610.015610
Komiske          2   1320.212800
værdifulde       2    805.007805

In [162]:
showcoll(coll40)

              counts          diff
graaskaldede       3  34493.264754
velmente           4   6343.588920
Ornamenter         2   5410.708197
velmeente          4   4486.928749
værdifulde         2   2243.464374
ufortjent          2   1642.536417
Yttringer          6   1333.073034
begeistrede        2   1022.022659
Fly                2    779.508808
Norriges           3    570.136608
fremsatte          2    363.565373
Meninger           2    313.931875
utallige           2    308.664562
Ideer              2    272.943737
Fædrelandets       2    220.580430
Klipper            3    209.685500
Sange              5    209.240308
57                 2    134.871025
Digte              3    126.002794
Forsøg             2     98.905419
lærte              2     81.907426
heel               2     79.022371
ægte               2     68.848832
helst              2     67.287520
Mange              3     66.301326
bedste             6     64.263185
Dronningen         2     59.076454
hine               2     36.807539
bør                2     29.671626
Vel                2     27.805937
Norges             2     16.705783
Ingen              2     14.345296
Navn               3     13.498978
nogle              3     12.757564
Af                 2     11.484834
fik                3      9.911146
sidste             2      9.561543
første             2      9.212945
andre              2      7.170412
Folk               2      6.940993
ere                3      6.713037
Som                2      6.301434
været              2      5.499016
se                 2      5.452080
deres              2      4.505831
mere               2      4.414573
sine               2      4.409494
endnu              2      4.239976
s                  2      3.503944
kun                2      3.234363